@startuml "Einlösen OTP in Kassen-APP und Ausstellen des PoPP-Token in LEI"
|PoPP-FdV/Kassen-APP|
start
:öffne PoPP-FdV;
:präsentiere 2D-Code;
|PoPP-Client|
:scanne 2D-Code;
:ermittle OTP aus 2D-Code;
|PoPP-Service|
:tausche OTP gegen PoPP-Token;
:ermittle PoPP-Token zu OTP;
:vervollständige PoPP-Token um Daten LEI;
fork
    :sende signierte PoPP-Token an PoPP-Client;
    |PoPP-Client|
    :lösche OTP vom PoPP-Client;
    :verwende PoPP-Token;
fork again
    |PoPP-Service|
    :lösche OTP vom PoPP-Service;
endfork
stop

@enduml