@startuml "Authentisierung mit GesundheitsID"
|PoPP-FdV/Kassen-APP|
start
:öffne PoPP-FdV;
|PoPP-Authorization-Server|
:initiiere Authentisierung des Versicherten;

|sektoraler IDP Kasse|
:startet Authentisierungsprozess;

|PoPP-FdV/Kassen-APP|
if (Consent PoPP vorhanden?) then (ja)
  
else (nein)
  :zeige Consentdialog;
endif

if (Consent PoPP erteilt?) then (ja)
  :zeige Authentisierungsmittel;
else (nein)
  :zeige Abbruchdialog;
  stop
endif
:authentisiert sich;

|sektoraler IDP Kasse|
:erstelle ID-Token mit KVNR;

|PoPP-Authorization-Server|
:erstelle Access-Token;
:sende Access-Token an FdV;

|PoPP-FdV/Kassen-APP|
:fordere OTP-Challange an;

|PoPP-Service|
:validiere Access-Token;
:entschlüssel Access-Token;
:extrahiere KVNT/IK-Nummer aus Access-Token;
:erstelle "halben Token";
:erstelle OTP-Challange;
:speichere OTP-Challange;

|PoPP-FdV/Kassen-APP|
:erstelle initiales OTP;
:speichere  initiales OTP;
:sende initiales OTP;

|PoPP-Service|
:validiere Access-Token;
:lade OTP-Challenge;
:aktualisiere OTP-Challange;
stop
@enduml