@startuml Einlösen OTP über Drittanbieter und Ausstellen des PoPP-Token
|Drittanbieter-APP\n(Vermittler Videosprechstunde \nVermittler Apotheke)|
start
:wähle Leistungserbringerinstitution\(Arzt, Apotheke);
:starte Vermittlung;
|PoPP-FdV\n(Kassen-APP, Drittanbieter-APP)|
:lade OTP vom PoPP-FdV;
if (Gültiges OTP vorhanden?) then (ja)
  
else (nein)
  :gehe zu checkin in PoPP-FdV\n(mit eGK, mit GesundheitsID);
endif

|Drittanbieter-APP\n(Vermittler Videosprechstunde \nVermittler Apotheke)|
:übermittle OTP und LE-Auswahl;
|Drittanbieter-backend|
:erstelle Kommunikationskanal zu Primärsystem der LEI;
|PoPP-Client|
:übermittle OTP;
|PoPP-Service|
:tausche OTP gegen PoPP-Token;
:ermittle PoPP-Token zu OTP;
:vervollständige PoPP-Token um Daten LEI;
fork
:sende signierte PoPP-Token an PoPP-Client;
|PoPP-Client|
:lösche OTP vom PoPP-Client;
:verwende PoPP-Token;
|Drittanbieter-backend|
:lösche OTP aus Drittanbieter-backend;
|Drittanbieter-APP\n(Vermittler Videosprechstunde \nVermittler Apotheke)|
:lösche OTP aus Videosprechstunden APP;
fork again
|PoPP-Service|
:lösche OTP vom PoPP-Service;
endfork
stop  

@enduml