@startuml
left to right direction
actor Versicherter as versicherter
actor "Leistungserbringer\n(Arzt, Apotheke)" as lei
actor "Anbieter LEI Vermittler\n(Videosprechstunde, Apotheken)" as ver

package "Authentisierung des Versicherten" {
	usecase "Authentisierung mit GesundheitsID (mobil)" as UCAuthGID
	usecase "Authentisierung mit eGK (mobil)" as UCAuthEGKMobil
	usecase "Authentisierung mit eGK (stationär eHealth-KT)" as UCAuthEGKeHKT
    usecase "Authentisierung mit eGK (stationär Standard-KT)" as UCAuthEGKSKT
}

package "Ausgabe des PoPP-Token" {
usecase "Ausstellung PoPP-Token über Einlösen OTP durch Versicherten\n(am Ort der Leistungserbringung)" as UCGetPoPPTokenLEI
usecase "Ausstellung PoPP-Token über Einlösen OTP durch Drittanbieter\n(Videosprechstunde, Apotheken)" as UCGetPoPPTokenDritt
usecase "Ausstellung PoPP-Token direkt \n(am Ort der Leistungserbringung)" as UCGetPoPPTokenDirekt
}


versicherter --> UCAuthGID
versicherter --> UCAuthEGKMobil
UCAuthEGKMobil <-- ver
versicherter --> UCAuthEGKeHKT
versicherter --> UCAuthEGKSKT
UCAuthEGKeHKT <-- lei
UCAuthEGKSKT <-- lei 

versicherter --> UCGetPoPPTokenLEI
UCGetPoPPTokenLEI <-- lei
versicherter --> UCGetPoPPTokenDirekt
UCGetPoPPTokenDirekt <-- lei
UCGetPoPPTokenDritt <-- lei
UCGetPoPPTokenDritt <-- ver


@enduml