@startuml
left to right direction
actor LEI as lei
package "LEI am PoPP Service registrieren/anmelden" {
  usecase "LEI registrieren" as UCLeiReg 
  usecase "LEI anmelden" as UCLeiAnm
  usecase "PoPP Token abrufen" as UCLeiToken
}

lei --> UCLeiReg
lei --> UCLeiAnm
lei --> UCLeiToken

@enduml