@startuml Initialisierung OTP

skinparam Shadowing false
skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam sequence {
    ArrowColor DodgerBlue
    ActorBorderColor DodgerBlue
    LifeLineBorderColor Blue

    ParticipantBackgroundColor #3483eb
    ParticipantBorderColor #3483eb
    ParticipantFontSize 14
    ParticipantFontColor White

    ActorBackgroundColor #3483eb
    ActorFontSize 14
    NoteBackgroundColor #3483eb
}

hide footbox
autonumber

box "Kassen-App/FdV"
participant "PoPP-FdV" as poppfdv #eb5e34
end box


box "OAuth2 Protected Resource"
participant "PoPP Service" as poppservice #eb5e34
participant "PoPP Repository" as popprepo #eb5e34
end box

' Init OTP-System
opt Initialisierung OTP
    poppfdv -> poppservice : getOTPChallenge(Access-Token)
    activate  poppservice
    poppservice -> poppservice : validate_AccessToken(KVNR, IKNummer)
    poppservice -> poppservice : generateOTPChallenge(KVNR, IKNummer, seq-num, seed)
    poppservice -> popprepo : createOTPChallengeRecord (KVNR, IKNummer, seq-num, seed)
    activate popprepo
    deactivate popprepo
    poppservice --> poppfdv : HTTP-200 \nOTPChallenge: otp-<algorithm identifier> <sequence integer> <seed> z.B.: "otp-sha1 5 abcdefghij"
    deactivate poppservice
    poppfdv -> poppfdv : computeInitialOTP(pass-phrase, seed, seq-num, dictionary): OTP_initial
    poppfdv -> poppfdv : initLocalOTPHolder (seed, seq-num, OTP_initial)
    activate  poppservice
    activate popprepo
    poppfdv -> poppservice : sendInitializationResponse(AccessToken, OTP_initial)
    poppservice -> popprepo : updateOTPChallengeRecord(KVNR, IKNummer, OTP_initial)
    poppservice --> poppfdv : HTTP-200
    deactivate  poppservice
    deactivate popprepo
    deactivate poppfdv
    ' Initialization complete
end

@enduml