@startuml Anmelden mit GesundheitsID

skinparam Shadowing false
skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam sequence {
    ArrowColor DodgerBlue
    ActorBorderColor DodgerBlue
    LifeLineBorderColor Blue

    ParticipantBackgroundColor #3483eb
    ParticipantBorderColor #3483eb
    ParticipantFontSize 14
    ParticipantFontColor White

    ActorBackgroundColor #3483eb
    ActorFontSize 14
    NoteBackgroundColor #3483eb
}

autonumber

actor Versicherte as versicherte

box "Kassen-App/FdV"
participant "PoPP-FdV" as poppfdv #eb5e34
participant "Authenticator Modul" as authenticator
end box
box "TI-Federation Relying Party"
participant "PoPP-Authorization Server" as poppauthz #eb5e34
end box

box "TI-Federation OpenID Provider"
participant "sektoraler IDP" as sekidp
end box

' Access Authorization for PoPP-FdV
opt Zugangsautorisierung für PoPP-FdV
versicherte --> poppfdv 
activate poppfdv 
poppfdv -> poppauthz : <color:red>GET sendAuthorizationRequest</color>
activate poppauthz

' Authentication via GID
opt Authentisierung mit GesundheitsID
poppauthz -> sekidp : POST pushedAuthorizationRequest
activate sekidp 
sekidp --> poppauthz : HTTP-200 \n(URI-PAR)
deactivate sekidp
poppauthz --> poppfdv : HTTP-302 \n(URI-PAR)
poppfdv -> authenticator : appCall (URI-PAR)
activate  authenticator
authenticator -> sekidp : AuthorizationRequest (URI-PAR)
activate sekidp
sekidp --> authenticator : AuthorizationCode
deactivate sekidp
authenticator --> poppfdv : HTTP-302 \nauthCode
deactivate authenticator 
poppfdv ->  poppauthz : POST sendAuthorizationCodeFdV(authCode)

' Exchange Authorization Code
poppauthz ->  sekidp : POST sendAuthorizationCode(authCode)
activate sekidp
sekidp -->  poppauthz : HTTP-200 \n(ID-Token)
deactivate sekidp
end
poppauthz -> poppauthz : <color:red>generateAccessToken(KVNR, IKNummer)</color>
poppauthz -> poppfdv : <color:red>Access-Token (for PoPP-Service Access)</color>
deactivate poppauthz
end
@enduml