@startuml OTP-Nutzung

skinparam Shadowing false
skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam sequence {
    ArrowColor DodgerBlue
    ActorBorderColor DodgerBlue
    LifeLineBorderColor Blue

    ParticipantBackgroundColor #3483eb
    ParticipantBorderColor #3483eb
    ParticipantFontSize 14
    ParticipantFontColor White

    ActorBackgroundColor #3483eb
    ActorFontSize 14
    NoteBackgroundColor #3483eb
}

hide footbox
autonumber
actor "Versicherter" as V
box "Kassen-App/FdV"
participant "PoPP-FdV" as poppfdv #eb5e34
end box

box "OAuth2 Protected Resource"
participant "PoPP Service" as poppservice #eb5e34
participant "PoPP Repository" as popprepo #eb5e34
end box

participant "PoPP-Client" as pc
actor "LEistungserbringer" as L

' Use OTP-System
opt Nutzung OTP
activate poppfdv
V -> poppfdv : navigate_to_LocalOTPHolder()
poppfdv -> poppfdv : render_OTP_QRcode()
poppfdv --> V : OTP_QR_Code_is_visible
V <-> L :                                                                      hello, here I have my care voucher :-)  OK, please put it here at the reader/scanner

L -> pc : activate_reader/scanner
activate pc
V -> pc : present_OTP_QR(OTP_QR)
pc -> pc : decode_OTP_QR(OTP_QR):OTP
activate poppservice
pc -> poppservice : redeem_OTP(OTP, Client Assertion ZT-JWT) 
poppservice -> poppservice : validate_OTP(OTP)
poppservice -> popprepo :  read_OTPChallengeRecord(OTP) : OTPChallengeRecord
popprepo --> poppservice : OTPChallengeRecord
poppservice -> poppservice : generate_PoPP-Token() : PoPP-Token
poppservice --> pc : PoPP-Token
poppservice -> popprepo : deleteOTPChallengeRecord(OTPChallengeRecord)
deactivate poppservice
deactivate popprepo
deactivate pc
deactivate poppfdv
deactivate L
deactivate V
end
@enduml