openapi: 3.1.0
info:
  title: PoPP Token Generation API healthcare practitioners software
  version: 1.0.0
  description: |
    This interface provides access to PoPP Token Generation API to be used by 
    healthcare practitioners software systems (Primärsysteme). It defines the 
    request, responses and other messages exchanged between the client and the 
    server to generate a PoPP token. 

paths:
  /popp/practitioner/api/v1/token-generation-ehc:
    summary: WebSocket endpoint for PoPP Token Generation
    description: |
      This endpoint allows the client to establish a WebSocket connection to the
      server and transmit messages to generate a PoPP token using the 
      eHealth-Card.
    get:
      summary: |
        Establish WebSocket Connection.
         
        Note: The actual connection is established using the WebSocket protocol 
        (wss://) and not via regular HTTP GET.
      operationId: connect
      responses:
        '101':
          description: Switching protocols to WebSocket
        '400':
          description: Bad request - unable to establish connection
      security:
        - oauth2Profiles: [ "token:generate" ]

components:
  schemas:
    StartMessage:
      type: object
      title: "Start proof process using electronic health card (eHC)"
      description: "Sent by the client to start the eHC proof process."
      properties:
        type:
          type: string
          const: "Start"
          description: "The constant type identifier for Start."
        version:
          type: string
          description: |
            The version of the eHC proof process to use, chosen by the client. 
            Server is expected to support this version.
            - version="1.0.0": actual value of "version"
        cardConnectionType:
          type: string
          enum:
            - "contact-standard"
            - "contact-connector"
            - "contactless-standard"
            - "contactless-connector"
          description: |
            The type of smartcard connection the client claims to use:
            
            * "contact-standard": contact based smartcard communication using
            ISO/IEC 7816-3 protocol T=1,
            connector is not involved in the communication with eHC
            
            * "contactless-standard": contactless smartcard communication using
            a protocol from ISO/IEC 14443 series,
            connector is not involved in the communication with eHC
            
            * "contact-connector": contact based smartcard communication using
            ISO/IEC 7816-3 protocol T=1,
            a connector communicates with the eHC via an eHCT
            
            * "contactless-connector": contactless smartcard communication using
            a protocol from ISO/IEC 14443 series,
            a connector communicates with the eHC via an eHCT
        connectorSessionId:
          type: string
          description: |
            A unique identifier for the connector session, generated by the
            connector. 
            A 128-bit octet string identifying a connector's session consisting
            of one or more "StandardScenarioMessage". It is recommended to use
            UUID according to RFC 4122.
            The PoPP-Service will use this value as "StandardScenarioMessage.clientSessionId".
            If this property is absent here, then "StandardScenarioMessage.clientSessionId"
            will also be absent.
      examples:
        - type: "Start"
          version: "1.0.0"
          cardConnectionType: "contact-standard"
      required:
        - type
        - version
        - cardConnectionType

    StandardScenarioMessage:
      type: object
      title: "Bunch of commands to be executed by an eHC"
      description: |
        Sent by the server to the client to execute command APDU by the
        eHealth-Card (eHC).
      properties:
        version:
          type: string
          description: |
            Version of the scenario message.
            - version = "1.0.0": actual value of "version".
        clientSessionId:
          type: string
          description: session identifier for the scenario message.
        sequenceCounter:
          type: integer
          description: |
            An integer in range [0, 32767] preventing reply attacks within a
            sequence of "ConnectorScenarioMessage" i.e., a group of more than one
            "ConnectorScenarioMessage" where all those "ConnectorScenarioMessage"
            share the same "clientSessionId". The first "StandardScenarioMessage"
            in a sequence has "sequenceCounter=0". The "sequenceCounter" in the
            next "StandardScenarioMessage" is incremented by one.
        timeSpan:
          type: integer
          format: duration
          description: |
            An integer in range [0, 32767] indicating the time span in
            milliseconds for the PoPP-Service between receiving a
            "ScenarioResultMessage" till the (expected) send time of the next
            "StandardScenarioMessage".
            A Connector or client uses this information to detect a timeout.
            The special value "timeSpan=0" indicates that this is the last
            "StandardScenarioMessage" in a sequence.
        steps:
          type: array
          description: List of steps in the scenario.
          items:
            $ref: "#/components/schemas/ScenarioStep"
      required:
        - version
        - clientSessionId
        - sequenceCounter
        - timeSpan
        - steps

    ScenarioStep:
      type: object
      properties:
        commandApdu:
          type: string
          description: ISO/IEC 7816-4 command APDU as hexadecimal string.
        expectedStatusWords:
          type: array
          description: List of expected status words as hexadecimal strings.
          items:
            type: string
      examples:
        - commandApdu: "00a4040c"
          expectedStatusWords: ["9000", "6f00"]
      required:
        - commandApdu
        - expectedStatusWords

    ConnectorScenarioMessage:
      type: object
      title: "Encapsulates command APDU for an eGK, forwarded to a Connector"
      description: |
        JWT according to RFC 7519 with a StandardScenarioMessage as payload
      properties:
        version:
          type: string
          description: |
            Version of the scenario message.
            - version = "1.0.0": actual value of "version".
        signedScenario:
          type: string
          description: |
            JWT according to RFC 7519 with a StandardScenarioMessage as payload.
            The payload is signed by the PoPP-Service.
      examples:
        - version: "1.0.0"
          signedScenario: "eeDDD.ddf.sd"
      required:
        - version
        - signedScenario

    ScenarioResponseMessage:
      type: object
      properties:
        steps:
          type: array
          description: List of ISO/IEC 7816-4 response APDU as hexadecimal strings.
          items:
            type: string
      examples:
        - steps: ["9000"]
      required:
        - steps

    ErrorMessage:
      type: object
      title: "Error"
      description: | 
        Sent by the server to indicate an error.
      properties:
        type:
          type: string
          const: "Error"
          description: [FRA|SER] Why do we need this? The ErrorMessage already defines the type.
        errorCode:
          type: string
          description: "The error code."
        errorDetail:
          type: string
          description: "A human-readable error message."
      required:
        - errorCode

    TokenMessage:
      type: object
      title: "Token"
      description: | 
        Sent by the server to provide the client with a PoPP token.
      properties:
        type:
          type: string
          const: "Token"
          description: [FRA|SER] Why do we need this? The TokenMessage already defines the type.
        token:
          type: string
          description: "PoPP token as JWT compact serialization."
        pn:
          type: string
          description: "Prüfnachweis"
      required:
        - token
        - pn
    # PoPP Token Headers
    TokenHeaders:
      type: object
      title: "PoPP Token Headers"
      description: | 
        Schema for the headers of a PoPP token as contained in the JWT.
      properties:
        typ:
          type: string
          const: "vnd.telematik.popp+jwt"
          description: |
            The type of the token.
        alg:
          type: string
          description: | 
            The algorithm used to sign the token. Currently only ES256 is 
            supported.
          enum:
            - ES256
        kid:
          type: string
          description: |
            The key identifier of the key used to sign the token. 
            Key itself can be retrieved from the JWK endpoint of the PoPP
            server.
        x5c:
          type: array
          items:
            type: string
            description: |
              The X.509 certificate chain used to sign the token. The first 
              element is the certificate that was used to sign the token.
              Certificates are encoded in DER and base64 encoded as described in 
              https://datatracker.ietf.org/doc/html/rfc7517#section-4.7
      required:
        - typ
        - alg
        - kid
        - x5c
      examples:
        - typ: "vnd.telematik.popp+jwt"
          alg: "ES256"
          kid: "x_vW4LVDipvu8iUQ5alKsZLWtH6jh4eJ4c5offXtMV0"
          x5c: [ "MIIBI..." ]
    # PoPP Token Claims
    TokenClaims:
      type: object
      title: "PoPP Token Claims"
      description: | 
        Schema for the claims of a PoPP token as contained in the JWT.
      properties:
        version:
          type: string
          description: |
            The version of the PoPP token format.
        iss:
          type: string
          description: |
            The issuer of the token. The value must be the URL of the PoPP 
            server without the path and without a trailing slash.
        iat:
          type: integer
          description: |
            The time the token was issued, interpreted as described in
            https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6
        proofMethod:
          type: string
          description: |
            The proof method used.
            
            **healthid**:</br>
            "Gesundheits-ID via FdV (Frontend des Versicherten)" i.e., health-ID
            provided by a special mobile app.
            
            **ehc-practitioner-...**:</br>
            Proof by eHC via a PoPP-client, the PoPP-client authenticates to the
            PoPP-service by means of an institution ID (i.e., SMC-B).
            
            **ehc-provider-...**:</br>
            Proof by eHC via an arbitrary mobile app, the mobile app connects
            directly to the PoPP-service.
            
            **ehc-...-trustedchannel-read-x509**:</br>
            This is the preferred method of proof for an eHC G2.1, contact-based
            communication.
            The PoPP-service establishes a trusted channel to the eHC and uses
            that channel for (authentically) reading an X.509 certificate.

            **ehc-...-cvc-authenticated-database-hash**:</br>
            This is the only possibly method of proof for an eHC G2.1, contactless
            communication.
            The PoPP-service authenticates the eHC and reads the X.509 certificate.
            Because reading the X.509 certificate here is non-authentic (from the
            PoPP-service point of view), the PoPP-service uses a database to check
            if the CV-certificate used for authenticating the eHC corresponds
            to the presented X.509 certificate.
            
            **ehc-...-user-x509**:</br>
            This is the preferred method of proof for an eHC G3.x, contactless
            or contact-based (no eHC PIN involved).
            The PoPP-service uses a challenge-response method where the private
            key corresponding to the X.509 certificate signs the challenge and
            that X.509 contains the information required for PoPP-token
            generation.

            **ehc-...-owner-x509**: (backlog, to-be-discussed)</br>
            Same as **ehc-...-user-x509** but another identity from the eHC is
            used where the user is requested to present a PIN.
            This way it is possible to distinguish between the owner of the eHC
            (card-holder) and a user of the eHC (deputy, agent, proxy).
          enum:
            - "healthid"
            - "ehc-practitioner-trustedchannel-read-x509"
            - "ehc-practitioner-cvc-authenticated-database-hash"
            - "ehc-practitioner-user-x509"
            - "ehc-practitioner-owner-x509"
            - "ehc-provider-trustedchannel-read-x509"
            - "ehc-provider-cvc-authenticated-database-hash"
            - "ehc-provider-user-x509"
            - "ehc-provider-owner-x509"
        patientProofTime:
          type: integer
          description: |
            The time the patient proof was performed, interpreted as described 
            in https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6
            
            * For proof methods with eHC this is the time the eHC was used.
            * For proof methods with HealthID this is the time the identity 
            was verified using the OpenID Connect.
        patientId:
          type: string
          description: |
            The patient identifier (KVNR).
        insurerId:
          type: string
          description: |
            The insurer identifier (IKNR).
        actorId:
          type: string
          description: |
            The actor identifier (Telematik-ID).
        actorProfessionOid:
          type: string
          description: |
            Profession OID of the actor.
      required:
        - version
        - iat
        - proofMethod
        - patientProofTime
        - patientId
        - insurerId
        - actorId
        - actorProfessionOid
      examples:
        - version: 1
          iss: "https://popp.example.com"
          iat: 1722593256
          proofMethod: "ehc-practitioner-trustedchannel-read-x509"
          patientProofTime: 1722593255
          patientId: "X123456789"
          insurerId: "123456789"
          actorId: "1-2012345678"
          actorProfessionOid: "1.2.276.0.76.4.50"

  securitySchemes:
    oauth2Profiles:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/auth
          tokenUrl: https://auth.example.com/token
          scopes:
            token:generate: Generate PoPP tokens

# Editor's notes: TODO This comment SHALL be deleted before publication. TODO
# 1. The following messages have a property "type" duplicating the type of
#    message:
#    - StartMessage, see line 40
#    - ErrorMessage, see line 202
#    - TokenMessage, see line 221
# 2. The following messages do NOT have a property "type":
#    - StandardScenarioMessage, see line 101 ff
#    - ConnectorScenarioMessage, see line 160 ff
#    - ScenarioResponseMessage, see line 183 ff
# 3. It seems either all messages have a property "type" or no message at all.
# 4. "TokenMessage" contains a JWT thing which is specified further as
#    "TokenHeader" and "TokenClaims".
#    It seems that seen as a payload in a JWT "StandardScenarioMessage" is
#    similar to "TokenClaims". But there is no correspondence to "TokenHeaders"
#    for a "ConnectorScenarioMessage". Is there something missing like
#    "ConnectorScenarioHeader"?
