openapi: 3.1.0
info:
  title: PoPP Token Generation API healthcare practitioners software
  version: 0.0.1
  description: |
    This interface provides access to PoPP Token Generation API to be used by 
    healthcare practitioners software systems (Primärsysteme). It defines the 
    request, responses and other messages exchanged between the client and the 
    server to generate a PoPP token. 

paths:
  /popp/practitioner/api/v1/token-generation-ehc:
    summary: WebSocket endpoint for PoPP Token Generation
    description: |
      This endpoint allows the client to establish a WebSocket connection to the
      server and transmit messages to generate a PoPP token using the 
      eHealth-Card.
    get:
      summary: |
        Establish WebSocket Connection.
         
        Note: The actual connection is established using the WebSocket protocol 
        (wss://) and not via regular HTTP GET.
      operationId: connect
      responses:
        '101':
          description: Switching protocols to WebSocket
        '400':
          description: Bad request - unable to establish connection
      security:
        - oauth2Profiles: [ "token:generate" ]

  /popp/practitioner/api/v1/token-generation-tan:   
    post:
      operationId: getPoPPToken
      summary: Create and send PoPP Token. 
      description: This endpoint allows the client to generate a PoPP token using a TAN.
      requestBody:
        required: true
        content: 
          application/json:
           schema:
            $ref: '#/components/schemas/TokenTanRequest'
            
      responses:
        '200':
          $ref: '#/components/responses/TokenResponse200'
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '404':
          $ref: '#/components/responses/Error404NotFound'
        '500':
          $ref: '#/components/responses/Error500InternalError'
      
      security: 
        - oauth2Profiles: [ "token:generate" ]

components:
  schemas:
    StartMessage:
      type: object
      title: "Start proof process using electronic health card (eHC)"
      description: "Sent by the client to start the eHC proof process."
      properties:
        type:
          type: string
          const: "Start"
          description: "The constant type identifier for Start."
        version:
          type: integer
          description: |
            The version of the eHC proof process to use, chosen by the client. 
            Server is expected to support this version.
        cardConnectionType:
          type: string
          enum:
            - "contact-standard"
            - "contact-connector"
            - "contactless-standard"
            - "contactless-connector"
          description: |
            The type of smartcard connection the client claims to use:
            
            * "contact-standard": contact based smartcard communication using
            ISO/IEC 7816-3 protocol T=1,
            connector is not involved in the communication with eHC
            
            * "contactless-standard": contactless smartcard communication using
            a protocol from ISO/IEC 14443 series,
            connector is not involved in the communication with eHC
            
            * "contact-connector": contact based smartcard communication using
            ISO/IEC 7816-3 protocol T=1,
            a connector communicates with the eHC via an eHCT
            
            * "contactless-connector": contactless smartcard communication using
            a protocol from ISO/IEC 14443 series,
            a connector communicates with the eHC via an eHCT
        clientSessionId:
          type: string
          description: | 
            A unique identifier for the client session, generated by the client.
            UUID v4 is recommended.
      examples:
        - type: "Start"
          version: 1
          cardConnectionType: "contactStandard"
          clientSessionId: "123e4567-e89b-12d3-a456-426614174000"

      required:
        - type
        - version
        - cardConnectionType
        - clientSessionId

    ScenarioMessage:
      type: object
      title: "Bunch of commands to be executed by an eHC"
      description: |
        Sent by the server to the client to execute a scenario on the
        eHealth-Card (eHC). Based on the cardConnectionType indicated in the
        prior StartMessage the server will provide either a scenario as an 
        array or a signed and encoded string.

        If the client indicated in its "StartMessage -> cardConnectionType" that
        the eHC is connected using a standard card reader ("...-standard"), 
        then the server will send a scenario as an array in `scenario` property
        where the array has at least two elements.

        If the client indicated in its "StartMessage -> cardConnectionType" that
        the eHC is connected using a eHealth-Cardterminal (eHCT) and connector 
        ("...-connector"), then the server will send a signed scenario as a string 
        `signedScenario` property.

        Either `scenario` or `signedScenario` is present, but not both.
      properties:
        type:
          type: string
          const: "Scenario"
          description: "The constant type identifier for Scenario Message"
        scenario:
          type: array
          items:
            type: string
            description: |
              hexadecimal characters [0-9a-f] either encoding expected
              status words or command APDU(s)
              
              **Background:**<br>
              A smartcard acts like a server (request-response), waits for
              commands, executes them and answers with a corresponding response.
              According to ISO/IEC 7816-3 a response APDU from a smartcards
              always contains a status word consisting of four nibbles where the
              most significant nibble is either '6' or '9'.
              According to [gemSpec_COS] no command APDU has a most significant
              nibble with values '6' or '9'.
              
              **Bunch of command APDU as an array:**<br>
              To speed up the process of executing smartcard commands successive
              command APDU are sent together as a scenario to minimize waiting
              times caused by network latency.
              
              **Expected status word:**<br>
              A smartcard status word possibly indicates errors. If such an
              error occurs it is worthless to send the remaining command APDUs
              of a scenario. To help the client to distinguish between normal
              smartcard operation and error situations a scenario also contains
              one or more status words combined into expectedStatusWords (ESW).
              
              **Layout of the array:**<br>
              The first element in the array (if present) contains ESW. ESW
              indicates the expected status words of a smartcard for normal
              operation.
              The status words in an ESW indicate what status words are expected
              and possibly occur during normal operation for the following
              command APDU. If another array element contains ESW, then the
              status words from that ESW replaces the expected status word(s)
              from a former ESW.
              Each array element, which is not ESW, contains a command APDU to
              be sent to a smartcard. If the status word in the corresponding
              response APDU is not element in ESW, then an error occurred and it
              is worthless to continue with further command APDU.
              If an array element has a most significant nibble of value '6' or
              '9' then that array element encodes ESW, otherwise that array
              element encoded a command APDU.
              
              **Explaining example 1:**<br>
              The purpose of example 1 is to show how the array `scenario` is
              encoded. Thus, the focus is not to do something meaningfull.
              1. The 1st element encodes ESW with one status word '9000'=NoError.
                This status words indicates the expected status word if the
                following command APDU are processed by a smart card for normal
                operation.
              2. The 2nd element is a command APDU (SELECT) for selecting the
                master file (MF) of a smartcard.
              3. The 3rd element is a command APDU (READ BINARY) for reading from
                offset='02' 3='03' bytes from EF.Version2.
              4. The 4th element encodes ESW with two status words. These two
                status words replace the status word(s) from a former ESW:
                a. '9000'=NoError
                b. '6281'=CorruptDataWarning
              5. The 5th element is a command APDU (READ BINARY) for reading the
                content of EF.C.eGK.AUT_CVC.E256.
        signedScenario:
          type: string
          description: |
            Base64 encoded BER-TLV structure, sent by the server only and only
            if the client indicated in its "StartMessage -> cardConnectionType"
            either
            - "contact-connector" or
            - "contactless-connector".
            
            The client forwards the signed message to a connector. The connector
            executes the scenario with a smartcard attached to an
            eHealth-Cardterminal.
      required:
        - type
      examples:
        - type: "Scenario"
          scenario: [ "9000", "00a4040c", "00b0910203", "90006281", "00b0860000" ]
        - type: "Scenario"
          signedScenario: "QkVSLVRMVgo="

    ScenarioResponseMessage:
      type: object
      title: "ScenarioResponse"
      description: |
        Sent by the client in response to a Scenario message.
      properties:
        type:
          type: string
          const: "ScenarioResponse"
          description: "The constant type identifier for ScenarioResponse."
        responses:
          type: array
          description: |
            The responses from the smartcard.
            The 1st element corresponds to the 1st command APDU from a Scenario.
            The n-th element corresponds to the n-th command APDU from a Scenario.
          items:
            type: string
            description: |
              Response from the smartcard encoded in hexadecimal characters
              [0-9a-f]. Contains at least 4 characters (status word).
      required:
        - type
        - responses

    ErrorMessage:
      type: object
      title: "Error"
      description: | 
        Sent by the server to indicate an error.
      properties:
        type:
          type: string
          const: "Error"
          description: "The constant type identifier for Error."
        errorCode:
          type: string
          description: "The error code."
        errorDetail:
          type: string
          description: "A human-readable error message."
      required:
        - type
        - errorCode

    TokenMessage:
      type: object
      title: "Token"
      description: | 
        Sent by the server to provide the client with a POPP token.
      properties:
        type:
          type: string
          const: "Token"
          description: "The constant type identifier for Token."
        token:
          type: string
          description: "POPP token as JWT compact serialization."
        pn:
          type: string
          description: "Prüfnachweis"

      required:
        - type
        - token
        - pn
    # PoPP Token Headers
    TokenHeaders:
      type: object
      title: "POPP Token Headers"
      description: | 
        Schema for the headers of a PoPP token as contained in the JWT.
      properties:
        typ:
          type: string
          const: "vnd.telematik.popp+jwt"
          description: |
            The type of the token.
        alg:
          type: string
          description: | 
            The algorithm used to sign the token. Currently only ES256 is 
            supported.
          enum:
            - ES256
        kid:
          type: string
          description: |
            The key identifier of the key used to sign the token. 
            Key itself can be retrieved from the JWK endpoint of the PoPP
            server.
        x5c:
          type: array
          items:
            type: string
            description: |
              The X.509 certificate chain used to sign the token. The first 
              element is the certificate that was used to sign the token.
              Certificates are encoded in DER and base64 encoded as described in 
              https://datatracker.ietf.org/doc/html/rfc7517#section-4.7
      required:
        - typ
        - alg
        - kid
        - x5c
      examples:
        - typ: "vnd.telematik.popp+jwt"
          alg: "ES256"
          kid: "x_vW4LVDipvu8iUQ5alKsZLWtH6jh4eJ4c5offXtMV0"
          x5c: [ "MIIBI..." ]
    # PoPP Token Claims
    TokenClaims:
      type: object
      title: "POPP Token Claims"
      description: | 
        Schema for the claims of a PoPP token as contained in the JWT.
      properties:
        version:
          type: string
          description: |
            The version of the PoPP token format.
        iss:
          type: string
          description: |
            The issuer of the token. The value must be the URL of the PoPP 
            server without the path and without a trailing slash.
        iat:
          type: integer
          description: |
            The time the token was issued, interpreted as described in
            https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6
        proofMethod:
          type: string
          description: |
            The proof method used.
            
            **healthid**:</br>
            "Gesundheits-ID via FdV (Frontend des Versicherten)" i.e., health-ID
            provided by a special mobile app.
            
            **ehc-practitioner-...**:</br>
            Proof by eHC via a PoPP-client, the PoPP-client authenticates to the
            PoPP-service by means of an institution ID (i.e., SMC-B).
            
            **ehc-provider-...**:</br>
            Proof by eHC via an arbitrary mobile app, the mobile app connects
            directly to the PoPP-service.
            
            **ehc-...-trustedchannel-read-x509**:</br>
            This is the preferred method of proof for an eHC G2.1, contact-based
            communication.
            The PoPP-service establishes a trusted channel to the eHC and uses
            that channel for (authentically) reading an X.509 certificate.

            **ehc-...-cvc-authenticated-database-hash**:</br>
            This is the only possibly method of proof for an eHC G2.1, contactless
            communication.
            The PoPP-service authenticates the eHC and reads the X.509 certificate.
            Because reading the X.509 certificate here is non-authentic (from the
            PoPP-service point of view), the PoPP-service uses a database to check
            if the CV-certificate used for authenticating the eHC corresponds
            to the presented X.509 certificate.
            
            **ehc-...-user-x509**:</br>
            This is the preferred method of proof for an eHC G3.x, contactless
            or contact-based (no eHC PIN involved).
            The PoPP-service uses a challenge-response method where the private
            key corresponding to the X.509 certificate signs the challenge and
            that X.509 contains the information required for PoPP-token
            generation.

            **ehc-...-owner-x509**: (backlog, to-be-discussed)</br>
            Same as **ehc-...-user-x509** but another identity from the eHC is
            used where the user is requested to present a PIN.
            This way it is possible to distinguish between the owner of the eHC
            (card-holder) and a user of the eHC (deputy, agent, proxy).
          enum:
            - "healthid"
            - "ehc-practitioner-trustedchannel-read-x509"
            - "ehc-practitioner-cvc-authenticated-database-hash"
            - "ehc-practitioner-user-x509"
            - "ehc-practitioner-owner-x509"
            - "ehc-provider-trustedchannel-read-x509"
            - "ehc-provider-cvc-authenticated-database-hash"
            - "ehc-provider-user-x509"
            - "ehc-provider-owner-x509"
        patientProofTime:
          type: integer
          description: |
            The time the patient proof was performed, interpreted as described 
            in https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6
            
            * For proof methods with eHC this is the time the eHC was used.
            * For proof methods with HealthID this is the time the identity 
            was verified using the OpenID Connect.
        patientId:
          type: string
          description: |
            The patient identifier (KVNR).
        insurerId:
          type: string
          description: |
            The insurer identifier (IKNR).
        actorId:
          type: string
          description: |
            The actor identifier (Telematik-ID).
        actorProfessionOid:
          type: string
          description: |
            Profession OID of the actor.
      required:
        - version
        - iat
        - proofMethod
        - patientProofTime
        - patientId
        - insurerId
        - actorId
        - actorProfessionOid
      examples:
        - version: 1
          iss: "https://popp.example.com"
          iat: 1722593256
          proofMethod: "ehc-practitioner-trustedchannel-read-x509"
          patientProofTime: 1722593255
          patientId: "X123456789"
          insurerId: "123456789"
          actorId: "1-2012345678"
          actorProfessionOid: "1.2.276.0.76.4.50"

    TokenTanRequest:
      description: The short TAN or long TAN is the result of mobile authentication with eHealt-ID (GesundheitsID) or verification of en eHealth-Card.
      type: object
      properties:
        tan:
          description: short TAN or long TAN 
          type: string
          examples: ["123456"]
  
  securitySchemes:
    oauth2Profiles:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/auth
          tokenUrl: https://auth.example.com/token
          scopes:
            token:generate: Generate PoPP tokens
  
  
  responses:
    TokenResponse200:
      description: HttpStatus.OK (200)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenMessage'

    Error400BadRequest:
      description: HttpStatus.BAD_REQUEST (400)
      content:
        application/json:
          example:
            errorCode: malformedRequest
          schema:
            $ref: '#/components/schemas/ErrorMessage'

    Error403Forbidden:
      description: HttpStatus.FORBIDDEN (403)
      content:
        application/json:
          example:
            errorCode: invalAuth
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    
    Error404NotFound:
      description: HttpStatus.NOT_FOUND (404)
      content:
        application/json:
          example:
            errorCode: noResource
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    Error500InternalError:
      description:  HttpStatus.INTERNAL_SERVER_ERROR (500)
      content:
        application/json:
          example:
            errorCode: internalError
          schema:
            $ref: '#/components/schemas/ErrorMessage'