openapi: 3.1.0
title: PoPP Token Generation API for eHealth-Card
description: |
  This interface provides access to PoPP Token Generation API using the eHealth-Card.
  It defines the messages exchanged between the client and the server to generate a PoPP token. 
  The messages are sent over a web socket connection.

paths:
  /popp/practitioner/api/v1/token-generation-ehc:
    summary: WebSocket endpoint for PoPP Token Generation 
    description: |
      This endpoint allows the client to establish a WebSocket connection to the server and transmit messages to generate a PoPP token using the eHealth-Card.
    get:
      summary: |
        Establish WebSocket Connection. 
        
        Note: The actual connection is established using the WebSocket protocol (wss://) and not via regular HTTP GET.
      operationId: connect
      responses:
        '101':
          description: Switching protocols to WebSocket
        '400':
          description: Bad request - unable to establish connection


components:
  schemas:
    StartMessage:
      type: object
      title: "Start proof process using electronic health card (eHC)"
      description: "Sent by the client to start the eHC proof process."
      properties:
        type:
          type: string
          const: "Start"
          description: "The constant type identifier for Start."
        version:
          type: integer
          description: "The version of the eHC proof process to use, chosen by the client. Server is expected to support this version."
        cardConnectionType:
          type: string
          enum: [ "contact-standard", "contact-connector", "contactless-standard", "contactless-connector" ]
          description: |
            The type of smartcard connection the client claims to use:
            
            * contactStandard: contact based smartcard communication using
            ISO/IEC 7816-3 protocol T=1,
            connector is not involved in the communication with eHC
            
            * contactlessStandard: contactless smartcard communication using
            a protocol from ISO/IEC 14443 series,
            connector is not involved in the communication with eHC
            
            * contactConnector: contact based smartcard communication using
            ISO/IEC 7816-3 protocol T=1,
            a connector communicates with the eHC via an eHCT
            
            * contactlessConnector: contactless smartcard communication using
            a protocol from ISO/IEC 14443 series,
            a connector communicates with the eHC via an eHCT
        clientSessionId:
          type: string
          description: "A unique identifier for the client session, generated by the client. UUID v4 is recommended."
      examples:
        - type: "Start"
          version: 1
          cardConnectionType: "contactStandard"
          clientSessionId: "123e4567-e89b-12d3-a456-426614174000"

      required:
        - type
        - version
        - cardConnectionType
        - clientSessionId

    ScenarioMessage:
      type: object
      title: "Sent by the server as a request to the client to execute a scenario on the smartcard."
      description: |
        Base64 encoded BER-TLV structure containing the scenario
        to be executed by the smartcard
      properties:
        type:
          type: string
          const: "Scenario"
          description: "The constant type identifier for Scenario."
        encoded:
          type: string
          description: "The encoded scenario data."
      required:
        - type
        - encoded

    ScenarioResponseMessage:
      type: object
      title: "ScenarioResponse"
      description: "Sent by the client in response to a Scenario message."
      properties:
        type:
          type: string
          const: "ScenarioResponse"
          description: "The constant type identifier for ScenarioResponse."
        responses:
          type: array
          items:
            type: string
            description: |
              Response from the smartcard encoded in hexadecimal characters.
              Contains at least 4 characters (status word).
          description: |
              The responses from the smartcard, one for each command in the scenario

      required:
        - type
        - responses

    ErrorMessage:
      type: object
      title: "Error"
      description: "Sent by the server to indicate an error."
      properties:
        type:
          type: string
          const: "Error"
          description: "The constant type identifier for Error."
        errorCode:
          type: string
          description: "The error code."
        errorDetail:
          type: string
          description: "A human-readable error message."
      required:
        - type
        - errorCode

    TokenMessage:
      type: object
      title: "Token"
      description: "Sent by the server to provide the client with a POPP token."
      properties:
        type:
          type: string
          const: "Token"
          description: "The constant type identifier for Token."
        token:
          type: string
          description: "POPP token as JWT compact serialization."
        pn:
          type: string
          description: "Prüfnachweis"

      required:
        - type
        - token
        - pn
